<?php

namespace App\Http\Controllers;

use App\Models\Product;
use App\Models\PurchaseLot;
use App\Models\StockMovement;
use App\Traits\LogsActivity;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    use LogsActivity;
    public function create()
    {
        return view('products.create');
    }

    public function index(Request $request)
    {
        $query = Product::query();
        $searchQuery = $request->query('q');

        // Search filter
        if (!empty($searchQuery)) {
            $query->where(function($q) use ($searchQuery) {
                $q->where('name', 'like', "%{$searchQuery}%")
                  ->orWhere('sku', 'like', "%{$searchQuery}%");
            });
        }

        // For autocomplete AJAX requests
        if ($request->wantsJson() || $request->ajax()) {
            $suggestions = $query->orderBy('name')
                ->limit(10)
                ->get(['name', 'sku'])
                ->map(function($product) {
                    return [
                        'label' => $product->name . ($product->sku ? ' (' . $product->sku . ')' : ''),
                        'value' => $product->name
                    ];
                });
            return response()->json($suggestions);
        }

        // Pagination per 10 produk
        $products = $query->orderBy('name')->paginate(10)->appends(['q' => $searchQuery]);
        
        return view('inventory', compact('products', 'searchQuery'));
    }

    public function edit($id)
    {
        $product = Product::findOrFail($id);
        return view('products.edit', compact('product'));
    }

    public function store(Request $request)
    {
        $data = $request->validate([
            'name' => ['required','string','max:255'],
            'sku' => ['nullable','string','max:100','unique:products,sku'],
            'current_stock' => ['nullable','integer','min:0'],
            'cost_price' => ['nullable','numeric','min:0'],
            'sale_price' => ['nullable','numeric','min:0'],
        ]);

        $product = Product::create([
            'name' => $data['name'],
            'sku' => $data['sku'] ?? null, // Will be auto-generated by model if empty
            'current_stock' => $data['current_stock'] ?? 0,
            'cost_price' => $data['cost_price'] ?? 0,
            'sale_price' => $data['sale_price'] ?? 0,
            'min_stock_level' => 0,
        ]);

        // Log activity
        $this->logProductCreated($product->name, $product->sku);

        return redirect()->route('inventory')->with('status', 'Produk berhasil ditambahkan.');
    }

    public function restock(Request $request)
    {
        $data = $request->validate([
            'product_id' => ['required','integer','exists:products,id'],
            'quantity' => ['required','integer','min:1'],
            'cost_price' => ['required','numeric','min:0'],
        ]);

        $product = Product::find($data['product_id']);
        if(!$product){
            return redirect()->back()->with('error','Produk tidak ditemukan.');
        }

        // create purchase lot
        $lot = PurchaseLot::create([
            'product_id' => $product->id,
            'quantity_received' => $data['quantity'],
            'quantity_remaining' => $data['quantity'],
            'cost_price_per_unit' => $data['cost_price'],
        ]);

        // increment product stock
        $product->increment('current_stock', $data['quantity']);

        // record stock movement
        StockMovement::create([
            'product_id' => $product->id,
            'quantity' => $data['quantity'],
            'reason' => 'stock_in',
        ]);

        // Log activity
        $this->logStockRestock($product->name, $data['quantity']);

        return redirect()->route('inventory')->with('status', 'Stok berhasil ditambahkan.');
    }

    public function update(Request $request, $id)
    {
        $product = Product::findOrFail($id);

        $data = $request->validate([
            'name' => ['required','string','max:255'],
            'min_stock_level' => ['nullable','integer','min:0'],
            'cost_price' => ['nullable','numeric','min:0'],
            'sale_price' => ['nullable','numeric','min:0'],
        ]);

        $product->update([
            'name' => $data['name'],
            'min_stock_level' => $data['min_stock_level'] ?? $product->min_stock_level,
            'cost_price' => $data['cost_price'] ?? $product->cost_price,
            'sale_price' => $data['sale_price'] ?? $product->sale_price,
        ]);

        // Log activity
        $this->logProductUpdated($product->name, $product->sku);

        return redirect()->route('inventory')->with('status', 'Produk berhasil diperbarui.');
    }

    public function destroy($id)
    {
        $product = Product::findOrFail($id);
        $productName = $product->name;
        $productSku = $product->sku;
        
        // Cek apakah produk sudah pernah dijual (ada di sale_items)
        $hasSales = \DB::table('sale_items')
            ->where('product_id', $product->id)
            ->exists();
        
        if ($hasSales) {
            return redirect()->route('inventory')->with('error', 
                'Produk "' . $productName . '" tidak dapat dihapus karena sudah pernah dijual. Produk ini terhubung dengan riwayat transaksi penjualan.');
        }
        
        // Cek apakah ada stock movement
        $hasStockMovement = \DB::table('stock_movements')
            ->where('product_id', $product->id)
            ->exists();
        
        if ($hasStockMovement) {
            return redirect()->route('inventory')->with('error', 
                'Produk "' . $productName . '" tidak dapat dihapus karena memiliki riwayat pergerakan stok.');
        }
        
        // Jika aman, lakukan hard delete
        $product->delete();
        
        // Log activity
        $this->logProductDeleted($productName, $productSku);
        
        return redirect()->route('inventory')->with('status', 'Produk berhasil dihapus.');
    }
}
